# @changed 2023.01.26, 02:21
# @see https://eslint.org/docs/rules/
root: true
extends:
  - 'next/core-web-vitals'
env:
  es6: true
  browser: true
  jest: true
  node: true
  # dom: true
rules:
  no-unused-vars:
    - warn
    - argsIgnorePattern: ^_
  no-console: warn
  no-debugger: warn
  no-extra-semi: warn
  no-redeclare: warn
  no-undef: error
  no-unreachable: warn
  prefer-const: warn
  quotes:
    - warn
    - single
  semi:
    - warn
    - always
    # - omitLastInOneLineBlock: true
