# @changed 2023.01.26, 01:52
# @see https://eslint.org/docs/rules/
root: true
extends:
  - 'next/core-web-vitals'
env:
  es6: true
  browser: true
  jest: true
  node: true
  # dom: true
rules:
  # no-unused-private-class-members: warn
  no-unused-vars:
    - warn
    - argsIgnorePattern: ^_
  # DEBUG: Check rule behavior
  # no-magic-numbers: [
  #   "warn",
  #   {
  #     ignore: [
  #       -1,
  #       0,
  #       1
  #     ],
  #     ignoreArrayIndexes: true,
  #     ignoreDefaultValues: true
  #   }
  # ]
  no-console: warn
  no-debugger: warn
  no-extra-semi: warn
  no-redeclare: warn
  no-undef: error
  no-unreachable: warn
  prefer-const: warn
  quotes:
    - warn
    - single
  semi:
    - warn
    - always
    # - omitLastInOneLineBlock: true

